name: noteng
description: "2024 - DJUnicode - NOTENG"
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  youtube_player_flutter: ^9.0.0
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1
  image_picker: ^1.0.8
  file_picker: ^8.0.3
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  flutter_neat_and_clean_calendar: ^0.3.19+41
  lottie: ^3.1.2
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  flutter_rating_bar: ^4.0.1
  flutter_otp_text_field: ^1.1.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    # - assets/img/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
